config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  get '/auth/:provider/callback', to: "sessions#omniauth"

  get '/vintage', to: "bottles#vintage"

  
  resources :bottles do
    resources :reviews
  end
  
  resources :reviews
  
  resources :users do
    resources :bottles, shallow: true
  end
  
  resources :categories, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle.rb
class Bottle < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_many :users, through: :reviews
  validates :wine_name, :vintage, :winery, :region, :description, presence: true
  accepts_nested_attributes_for :category

  scope :alpha, -> { order(:wine_name) }
 # scope :year, ->(year) { where('vintage = ?', year) }

  

  def category_attributes=(attr)
    self.category = Category.find_or_create_by(attr) if !attr[:name].blank?
  end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :bottles
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :bottle
   
    validates :content, presence: true
    validates :user_id, presence: true
    validates :bottle_id, presence: true

end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
    has_many :bottles
    has_many :reviews
    has_many :reviewed_bottles, through: :reviews, source: :bottle
    has_many :categories, through: :bottles
    
    has_secure_password
    validates :username, :email, presence: true
    
    def self.find_with_omniauth(auth)
        self.find_or_create_by(uid: auth[:uid]) do |u|
            u.username = auth[:info][:name]
            u.email = auth[:info][:email]
            u.password = SecureRandom.hex(16)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
    
    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end


end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_bottle, only: [:show, :edit, :update]


    def new
      if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @bottle = @user.bottles.build
      else
        flash[:errors] = "bottle does not exist" if params[:user_id]
        @bottle = Bottle.new
      end
        @bottle.build_category
    end
    
    def index
      if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @bottles = @user.bottles.alpha
      else
        flash[:errors] = "bottle does not exist" if params[:user_id]
        @bottles = Bottle.alpha
      end
    end

    def create
      @bottle = current_user.bottles.build(bottle_params)
        if @bottle.save
           flash[:message] = "Entry successful"
           redirect_to bottle_path(@bottle)
        else
           render :new
        end
    end

    def edit
      redirect_to bottles_path if !@bottle || @bottle.user != current_user
      @bottle.build_category if !@bottle.category
    end
  
    def update 
      if @bottle.update(bottle_params)
        flash[:message] = "Entry successfully updated"
        redirect_to bottle_path(@bottle)
      else
        render :edit
      end
    end

    def show
        redirect_to bottles_path if !@bottle
    end

    def vintage
    end

    def destroy
      Bottle.find(params[:id]).destroy
      redirect_to bottles_path
   end

    private

    def bottle_params 
        params.require(:bottle).permit(:wine_name, :vintage, :winery, :region, :description, :category_id, category_attributes: [:name])
    end

    def set_bottle
      @bottle = Bottle.find_by_id(params[:id])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    def index
        @categories = Category.all.includes(:bottles)
    end
    
    def show
        @category = Category.find_by_id(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_review, only: [:edit, :update, :show]

    def index
        if params[:bottle_id] && @bottle = Bottle.find_by_id(params[:bottle_id])
          @reviews = @bottle.reviews
        else
          @reviews = Review.all
        end
    end
    
    def new
      if params[:bottle_id] && @bottle = Bottle.find_by_id(params[:bottle_id]) && !current_user
        @review = @bottle.reviews.build
      else
        @review = Review.new
      end
    end   

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
          flash[:message] = "Sucessfully created review"
            redirect_to reviews_path
        else
            render :new
        end
    end
    
    def edit
    end
    

    def update 
      if @review.update(review_params)
        flash[:message] = "Review successfully updated"
        redirect_to bottle_review_path(@review)
      else
        render :edit
      end
    end


    def show
      redirect_to bottle_review_path if !@review
    end


    def destroy
      Review.find(params[:id]).destroy
      redirect_to reviews_path
    end
  
        private
  
      def review_params 
        params.require(:review).permit(:content, :bottle_id)
      end

      def set_review
        @review = Review.find_by_id(params[:id])
      end
  end


  # search bottles index by bottle name and return matchings results

  # 1 add search bar and button to bottles index
  # 2 add a route to bring query to bottles index action
  # 3 writing a scope method to use query to filter bottles
  # 4 display new list of bottles

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def create 
      user = User.find_by(username: params[:user][:username])
      if user && user.authenticate(params[:user][:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:errors] = "Incorrect login info. Please try again."
        redirect_to login_path
      end
    end

    def destroy
    session.clear
        redirect_to root_path
    end

    def omniauth
      @user = User.find_with_omniauth(auth)
      if @user
          session[:user_id] = @user.id
          redirect_to user_path(@user)
      else
          flash[:errors] = "Please log in"
          redirect_to login_path
      end
    end

    private

    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          flash[:errors] = "Failed to create account: #{@user.errors.full_messages.to_sentence}"
          redirect_to signup_path
        end
    end

    def show 
      redirect_if_not_logged_in
      @user = User.find_by_id(params[:id])
      redirect_to '/' if !@user
    end


    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
     
    Choose a category: <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  <br>
    Or create a new category:
    <%= f.fields_for :category do |c| %>
        <% c.text_field :name %>
    <% end %>
<br>
<br>
<em>Write "0" for no vintage and  "?" or "NA" if not sure to fill in all fields. This can be edited later.</em>
<br>
<br>
    Wine Name:<br>
    <%= f.text_field :wine_name %><br>
    Vintage:<br>
    <%= f.text_field :vintage %><br>
    Region:<br>
    <%= f.text_field :region %><br>
    Winery:<br>
    <%= f.text_field :winery %><br>
    Description:<br>
    <%= f.text_area :description, cols:50, rows:10 %> <%= f.submit %>
<% end %>

app/views/bottles/edit.html.erb
<h1>Edit <%= @bottle.wine_name %></h1>

<%= render partial: "layouts/errors", locals: {object: @bottle} %>

<%= render partial: "bottles/form" %>

app/views/bottles/index.html.erb
<h1>BOTTLES INDEX</h1>

<ul>
<% @bottles.each do |b| %>
    <li>
        <%= link_to b.wine_name, bottle_path(b) %>
    </li>
<% end %>
</ul>

app/views/bottles/new.html.erb
<h1>Add a new bottle</h1>

<%= render partial: "layouts/errors", locals: {object: @bottle} %>

<%= render partial: "bottles/form" %>

app/views/bottles/show.html.erb
<h2><u><%= @bottle.wine_name %></h2></u>
<p>by: <%= link_to @bottle.user.username, user_path(@bottle.user) %></p>


<h3>Category: <%= @bottle.category.try(:name)%></h3>
<strong>Vintage:</strong> <%= @bottle.vintage %><br>
<strong>Winery:</strong> <%= @bottle.winery %><br>
<strong>Region:</strong> <%= @bottle.region %><br>
<strong>Description:</strong> <%= @bottle.description %>
<br>
<br>


  <% if @bottle.user == current_user %>
    <h4><%= link_to "Edit This Entry", edit_bottle_path(@bottle)%></h4>
    <%= button_to "Delete Entry", bottle_path(@bottle), method: :delete %> 
  <% end %>
  <p><%= link_to "Leave a Comment or Review", new_bottle_review_path(@bottle) %></p>
<br>

<h3>Comments & Reviews:</h3>
<% @bottle.reviews.each do |r| %>
<li>
  <strong><%= link_to r.user.username, bottle_review_path(@bottle, r) %></strong> says: "<%= r.content %>"
</li>
<% end %>

app/views/bottles/vintage.html.erb
Vintage show


<ul>
<% @bottles.each do |b| %>
    <li>
        <%= link_to b.wine_name, bottle_path(b) %>
    </li>
<% end %>
</ul>

app/views/categories/index.html.erb
<h1>Categories of Wines</h1>

<ul>
<% @categories.each do |c| %>
    <li> <%= link_to c.name, category_path(c) %></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<ul>
    <% @category.bottles.each do |b| %>
      <li>
      <%= link_to b.wine_name, bottle_path(b) %>
      </li>
    <% end  %>
</ul>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradeVine App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Neucha&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navigation">
    <p align="center">
      <% if logged_in? %>
      <%= link_to "Home", user_path(current_user) %> |
      <%= link_to "Submit a bottle", new_bottle_path %> |
      <%= link_to "All Bottles", bottles_path %> |
      <%= link_to "All Categories", categories_path %> |
      <%= link_to "All Reviews ", reviews_path %> |
      <%= link_to "Logout", logout_path, method: "delete" %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> |
        <%= link_to "Login", login_path %>
      <% end %>
    </div>

    <div class="wrapper">

      <% if flash[:message] %>
        <h3 style="color: rgb(63, 133, 0);"><em><%= flash[:message] %></h3></em>
      <% end %>
      <% if flash[:errors] %>
        <h3 style="color: rgb(199, 28, 28);"><em><%= flash[:errors] %></h3></em>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for(@review) do |f| %>
    <%= f.label :bottle %>
    <%= f.collection_select :bottle_id, Bottle.all, :id, :wine_name %>
    <br>
    <br>
    Review: <%= f.text_area :content, cols:30, rows:5 %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<% if @bottle %>
  <h1>Reviews for <%= @bottle.wine_name %></h1>
<% else %>
  <h1>All Reviews</h1>
<% end %>
<br>
<ul>
  <% @reviews.each do |r| %>
    <li><strong><%= link_to r.bottle.wine_name, bottle_path(r.bottle_id) %></strong></li>
    <strong><%= r.user.username %> says:</strong> "<%= r.content%>"
    <br>
    <br>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<% if @review.bottle %>
    <h1>New Review for <%= @review.bottle.wine_name %></h1>
<% else %>
    <h1>New Review</h1>
<% end %>


<%= render partial: "layouts/errors", locals: {object: @review} %>


<%= form_for([@review.bottle, @review]) do |f| %>
    <% if !@review.bottle %>
        <%= f.label :bottle %>
        <%= f.collection_select :bottle_id, Bottle.alpha, :id, :wine_name %>
    <% else %>
        <%= f.hidden_field :bottle_id %>
    <br>
    <% end %>
    <br>
    <br>
    Review:<br>
    <%= f.text_area :content, cols:30, rows:5 %>
    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h2>Review for: <%= link_to @review.bottle.wine_name, bottle_path(@review) %></h2>
<br>
<strong><%= @review.user.username %></strong> says: - <%= @review.content %>

<% if @review.user == current_user %>
  <p><%= link_to "Edit Review", edit_review_path(@review)%></p>
  <p><%= button_to "Delete Review", review_path(@review), method: :delete %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for (@user) do |f|%>
    <%= f.label :username %>
    <%= f.text_field :username %> |
    <%= f.label :email %>
    <%= f.email_field :email %> |
    <%= f.label :password %>
    <%= f.password_field :password %> |
    <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>


<%= link_to "My Bottles", user_bottles_path(current_user) %>


<h2>Plenty of bottles awaiting to be reviewed and commented on.</h2>

Do not forget to join a mailing list to know whenever new wines are in stock.